objectives = [{"Eight Weeks of Darkness": "Survive 8 rounds.",\
              "Kill Them": "There are 3 or fewer zombies at all non-colony locations combined.",\
              "Find a Cure": "Players have placed 2 med cards in storage for each player that started the game.",\
              "Home Sweet Home": "There are at least 10 barricades at the colony and 1 barricade at each non-colony location.",\
              "Raiding Party": "Deplete 2 non-colony locations of their item decks.",\
              "Leave It All Behind": "All non-exiled players must have 1 weapon equipped to a survivor they control. Players have placed 2 food cards in storage for each player that started the game.",\
              "Stockpile": "There must be at least 2 food tokens in the food supply for each non-exiled player. There must be at least 1 barricade at each colony entrance. Players have also placed 2 med cards, 2 trash cards and 2 fuel cards in storage.",\
              "Winter Has Come": "At the beginning of the colony phase a single player may place 1 fuel card in storage. If one is not placed, the game is over and the main objective has failed. If, on the 8th round of the game, there are 8 fuel cards in storage during the check main objective part of the colony phase, this main objective has been completed.",\
              "Too Many Mouths": "Survive 5 round.",\
              "We Need More Samples": "Every time a zombie is killed roll a die. If the die result is a 4 or higher add a zombie to the storage. Accumulate 3 zombies in storage for each player that started the game."}]

stories = [{"date": "January 30th", "entry": "This place is as dead as the things that hunt us. When we formed the colony here, we thought we could live off the town for years. But we misjudged what this place had to offer. I can only assume it's been hit by other survivors and much of the goods and supplies we should have been able to find are in short supply. Canned goods, ammunition, fuel... everything we need is in conspicuously small quantities. We need to move on, but it's just too cold. So we wait, praying for the weather to let up so we can get the convoy rolling again, and start the miserable search all over again. It seems like each time I'm ready to eat a bullet, a new crisis appears, and suddenly I'm fighting as if living is the only thing that matters."},\
           {"date": "January 15th", "entry": "I refused to believe it at first, but the proof is there for everyone to see. Twenty four hours has passed and Mel still hasn't risen. Sure the bites killed him, but they were grotesquely severe. What's important is they lacked the juice to bring him back. Optimism is raging through the colony like fire in a dry forest. We were already wondering why the ranks of the dead seemed to be thinning. Could our wildest hopes have come to pass? Has whatever force that animated the corpses finally left or died off? Should this be true, it changes everything. If we can only kill those dead that shamble through the town and around our walls, we might be able to spend the rest of our lives in peace. Finally! I'm not afraid to die fighting, but I don't want to die and become the very enemy I fought."},\
           {"date": "December 20th", "entry": "I sit here in silent shock. Could the answer be so simple? Has our great species been brought to the edge of extinction by a mutation of one of its simples and oldest viruses? If there are gods, surely they are laughing at us now. Or at least they laughedat each moment in my life when I failed to wash my hands. But what's next? I need a better lab. And supplies. I need to rally the others and have them bring me everything they can. At the very least I think I can immunize us, but even better, I think I might be able to eradicate this plague in one fell airborne swoop. I think back to that summer when I, drunk on youth and love, considered staying in Italy and saying to hell with finishing med school. How horrifying to think that a cheating Italian boyfriend may have been a critical factor in ending the greatest catastrophe to mankind!"},\
           {"date": "February 5th", "entry": "All of our hard work has rewarded us more than I could have hoped. Yesterday this was a refugee camp, and today it's an honest-to-God town. When people call it the Colony, there's no bitter irony in their voices, and that speaks volumes. Only problem is, all of our hard work has brought down a swarm of the dead upon us. Each day brings new invaders to our walls, and they wander the streets in town waiting for a living morsel to present itself. If we can just figure out a way to kill this swarm, build up our defenses and hopefully stop attracting more of them. Sure, we'll probably be dealing with stragglers for the rest of our days, but anything would be better than the horde we're dealing with now."},\
           {"date": "November 13th", "entry": "Winter will be upon us before we know it, and we don't want to be here when it arrives. The town doesn't seem to have been looted much - they must have been hit hard. We'll set up a camp here, then hunker down and see what we can find. We'll need to move quickly, and not just because of the weather. The dead seem to have caught wind of our presence, and we see more and more each day. If we lose people or waste supplies fighting those freaks off, then this whole raid will be for nothing. Our primary target for the search is fuel, but personally I'm hoping medical supplies are abundant. If I don't get this bite treated soon, someone's going to notice. Already I've got a light fever that won't go away, and once I start to sweat I just can't stop. All I need is some antibiotics or something. I just know it. There's no way I'm going out like those other fools. I won't let it happen."},\
           {"date": "February 21st", "entry": "It's us or them now. I hate that it's come to this - I really do. But our species isn't going to survive without staring down some terrible and hard truths. There's a core group of us and then there are the tagalongs. The core group makes all the tough calls. It does all the hard work. The tagalongs seem to just be there to eat our food and complain about their inconveniences. Screw them. I say when it's time to go we leave behind the bickering fools who thing every decision deserves a debate and a vote. I say we ditch the moaners who don't appreciate the concept of a meritocracy. Of course they don't like that idea - they don't do anything. Well my mind is made up, and I know the others will agree. We just need to make sure we act quickly when the opportunity presents itself."},\
           {"date": "December 16th", "entry": "This morning I stood on the watchtower (I still can't believe the thing hasn't collapsed) and looked out at the town. I pretended I couldn't see the dead that staggered through the streets, and it seemed lovely to me. Fog was rising from the ground in ghostlike wisps, and the crisp air that filled my lungs felt magnificent. I don't want to leave this place. Winter will be hard, but I'm already dreaming of what spring will bring. Maybe I'm a fool to find inspiration in the season where the Earth seems to wither and die, but it's always felt like starting over to me. Now is the time to hunker down and gather all the food we can. Now is when we build big walls our enemies cannot overcome. The snow shall melt and everything that's green will flourish and bloom again, and when it does, Spring shall find us not just alive but thriving."},\
           {"date": "November 28th", "entry": "We've been caught with our pants down just like I warned them. Anyone willing to keep their eyes open could have seen the warning signs. Early morning frosts. Rapidly changing weather. It was just a matter of time. Now winter is here and up to now we've only been concerning ourselves with food. The generators can keep us alive but they're useles without fuel. Yesterday one of the kids offered to drive into townto scavenge, and it was all I could do not to slap him. Drive? Doesn't that use fuel? Try walking - it will keep you warm at least. God help me, it's like the parable of the Ant and the Grasshopper, only in this scenario the ants will die right alongside their lazy companions."},\
           {"date": "February 10th", "entry": "Is today Groundhog's Day? I can't remember anymore. Weird how hunger lets one dwell on such trivial thoughts. Shouldn't every brain cell be conserved right now? The canned goods ran out a week ago, and the grains followed soon after. The chickens are gone and so is the last of the venison. We're living off what scraps we find in town, but they aren't enough. I've never thought myself an evil man, but God help me, my thoughts are dark of late. I know I'm not the only one. There just isn't enough food to go around, and it's hard not to feel bitter when it has to be shared with people who don't pull their own weight. These thoughts are wrong. I know that. It's no one's fault that the skills they possess belong to another world. Another time. Our intellectual capacity is what separates us from animals, yet when out most basic needs cannot be met, it's hard not to think and act like animals."},\
           {"date": "January 25th", "entry": "As if the colony needed to smell even worse! Now we're storing corpses in the sheds where we once kept our plentiful food stores. God, what I wouldn't give to taste a carrot again. You-know-who has on her bossy boots once more. I didn't like doctors before the world ended, and I don't like them now. She says studying the bodies might help her identify how to stop the plague. Yeah, right. Better to spend time figuring out the quickest, cheapest way to commit suicide. But whatever. Everyone else is excited to help, and maybe that's the real value of this little project. All this 'research' wil; do is tell us what we already know - the dead come back and try to eat you. Whoopty-freakin'-do. Still, if Her Royal Highness does come up with a cure, I'd better be the first in line to get it."}]